from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from pathlib import Path
from datetime import datetime
from app.config import DELIVERABLES_DIR

def create_approval_note(
    memo_no: str,
    subject: str,
    reference_doc: str,
    inspection_summary: dict,
    findings_table: list,
    recommendation: str,
    signatory_title: str = "Chief Inspection Officer (QA & Safety)",
    signatory_dept: str = "Directorate of Quality Assurance & Standards"
) -> str:
    """
    Generates a formal, standard Government of India / PSU Note Sheet / Approval Memorandum in .docx format.
    """
    doc = Document()

    # Document Title / Organization Header
    header = doc.add_paragraph()
    header.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run_org = header.add_run("GOVERNMENT OF INDIA / PSU ENTERPRISE\n")
    run_org.bold = True
    run_org.font.size = Pt(14)
    run_org.font.color.rgb = RGBColor(16, 44, 87) # Deep Navy

    run_sub = header.add_run("DEPARTMENT OF INDUSTRIAL DEFENCE & QUALITY ASSURANCE\nSOVEREIGN ENGINEERING WING")
    run_sub.font.size = Pt(10)
    run_sub.font.color.rgb = RGBColor(80, 80, 80)

    doc.add_paragraph("─" * 55).alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Note Sheet Title
    p_title = doc.add_paragraph()
    p_title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run_note = p_title.add_run("OFFICIAL NOTE SHEET / APPROVAL MEMORANDUM")
    run_note.bold = True
    run_note.font.size = Pt(12)
    run_note.underline = True

    # Memo Details Meta Table
    table_meta = doc.add_table(rows=3, cols=2)
    table_meta.alignment = WD_TABLE_ALIGNMENT.CENTER
    table_meta.autofit = True
    
    table_meta.rows[0].cells[0].text = f"Memo No: {memo_no}"
    table_meta.rows[0].cells[1].text = f"Date: {datetime.now().strftime('%d-%b-%Y')}"
    table_meta.rows[1].cells[0].text = f"Security Clearance: RESTRICTED / OFFICIAL"
    table_meta.rows[1].cells[1].text = f"Generated by: Sovereign AI Engine (Air-Gapped)"
    table_meta.rows[2].cells[0].text = f"Reference: {reference_doc}"
    table_meta.rows[2].cells[1].text = f"Action Type: Immediate Regulatory Approval"

    doc.add_paragraph()

    # Subject Section
    p_subj = doc.add_paragraph()
    r_subj_label = p_subj.add_run("SUBJECT: ")
    r_subj_label.bold = True
    p_subj.add_run(subject)

    # 1. Background & Inspection Context
    h1 = doc.add_heading("1. Background & Inspection Context", level=2)
    h1.paragraph_format.space_before = Pt(8)
    
    p_bg = doc.add_paragraph()
    p_bg.add_run(
        f"An inspection report ({reference_doc}) was processed and verified against internal sovereign SOP standards. "
        f"The telemetry, dimensional parameters, and physical tolerances were extracted and audited locally without external data transmission."
    )

    # 2. Findings & SOP Compliance Analysis Table
    h2 = doc.add_heading("2. Technical Findings vs SOP Standard Tolerances", level=2)
    
    if findings_table:
        table_f = doc.add_table(rows=1, cols=4)
        table_f.alignment = WD_TABLE_ALIGNMENT.CENTER
        table_f.style = "Table Grid"

        hdr_cells = table_f.rows[0].cells
        headers = ["Parameter", "Measured Value", "SOP Standard Limit", "Status / Compliance"]
        for idx, name in enumerate(headers):
            hdr_cells[idx].text = name
            for p in hdr_cells[idx].paragraphs:
                for run in p.runs:
                    run.bold = True
                    run.font.size = Pt(9.5)

        for row_data in findings_table:
            row_cells = table_f.add_row().cells
            row_cells[0].text = str(row_data.get("parameter", ""))
            row_cells[1].text = str(row_data.get("measured", ""))
            row_cells[2].text = str(row_data.get("limit", ""))
            status_text = str(row_data.get("status", ""))
            row_cells[3].text = status_text
            
            # Format text size
            for c in row_cells:
                for p in c.paragraphs:
                    for r in p.runs:
                        r.font.size = Pt(9)

    doc.add_paragraph()

    # 3. Comprehensive Evaluation & Reasoning
    doc.add_heading("3. Technical Evaluation & AI Reasoning Trail", level=2)
    p_eval = doc.add_paragraph()
    eval_text = inspection_summary.get("evaluation", "Detailed parametric analysis confirms critical deviations in bearing vibration metrics exceeding standard SOP limits.")
    p_eval.add_run(eval_text)

    # 4. Recommendation & Approval Order
    doc.add_heading("4. Final Recommendation & Regulatory Order", level=2)
    p_rec = doc.add_paragraph()
    r_rec = p_rec.add_run(f"RECOMMENDATION: {recommendation}\n")
    r_rec.bold = True
    p_rec.add_run(
        "Submitted for urgent administrative perusal, financial sanction, and issuance of immediate maintenance directives."
    )

    doc.add_paragraph()
    doc.add_paragraph()

    # Signature Block
    p_sign = doc.add_paragraph()
    p_sign.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    p_sign.add_run("_____________________________________\n").bold = True
    p_sign.add_run(f"(Digital Signature / Approval Stamp)\n").italic = True
    p_sign.add_run(f"{signatory_title}\n").bold = True
    p_sign.add_run(f"{signatory_dept}\n")
    p_sign.add_run(f"Verified Sovereign Node: LOCAL-IND-NODE-01")

    # Save to Deliverables Folder
    filename = f"Approval_Note_{memo_no.replace('/', '_')}.docx"
    filepath = DELIVERABLES_DIR / filename
    doc.save(str(filepath))

    return filename
