from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.enum.shapes import MSO_SHAPE
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Any, Optional
from app.config import DELIVERABLES_DIR

def create_executive_presentation(
    title: str,
    subtitle: str,
    classification: str = "RESTRICTED // OFFICIAL USE ONLY",
    slides_data: Optional[List[Dict[str, Any]]] = None,
    filename_prefix: str = "Executive_Briefing"
) -> str:
    """
    Generates a high-impact, professional Sovereign PowerPoint Presentation (.pptx).
    Follows enterprise defense aesthetic: Navy (#0F2C59), Slate (#1E293B), Gold (#F59E0B), and Emerald (#10B981).
    """
    prs = Presentation()
    prs.slide_width = Inches(13.333) # 16:9 widescreen
    prs.slide_height = Inches(7.5)

    # Color definitions
    NAVY = RGBColor(15, 44, 89)
    DARK_BG = RGBColor(10, 20, 38)
    CARD_BG = RGBColor(24, 38, 64)
    TEXT_LIGHT = RGBColor(241, 245, 249)
    TEXT_MUTED = RGBColor(148, 163, 184)
    ACCENT_GOLD = RGBColor(245, 158, 11)
    ACCENT_EMERALD = RGBColor(16, 185, 129)
    ACCENT_RED = RGBColor(239, 68, 68)

    blank_slide_layout = prs.slide_layouts[6]

    # Helper: Add slide background
    def set_slide_background(slide, color=DARK_BG):
        bg = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, 0, prs.slide_width, prs.slide_height)
        bg.fill.solid()
        bg.fill.fore_color.rgb = color
        bg.line.fill.background()
        return bg

    # Helper: Add header & footer
    def add_header_footer(slide, slide_title: str, slide_num: int):
        # Header banner
        header = slide.shapes.add_textbox(Inches(0.8), Inches(0.4), Inches(11.733), Inches(0.8))
        tf = header.text_frame
        tf.word_wrap = True
        p = tf.paragraphs[0]
        p.text = slide_title.upper()
        p.font.size = Pt(22)
        p.font.bold = True
        p.font.color.rgb = TEXT_LIGHT

        # Classification stamp top-right
        stamp = slide.shapes.add_textbox(Inches(8.5), Inches(0.4), Inches(4.0), Inches(0.4))
        p_stamp = stamp.text_frame.paragraphs[0]
        p_stamp.text = f"[{classification}]"
        p_stamp.font.size = Pt(10)
        p_stamp.font.bold = True
        p_stamp.font.color.rgb = ACCENT_GOLD
        p_stamp.alignment = PP_ALIGN.RIGHT

        # Footer
        footer = slide.shapes.add_textbox(Inches(0.8), Inches(6.9), Inches(11.733), Inches(0.4))
        p_foot = footer.text_frame.paragraphs[0]
        p_foot.text = f"SOVEREIGN AGENTIC AI WORKBENCH  |  {datetime.now().strftime('%d-%b-%Y')}  |  SLIDE {slide_num}"
        p_foot.font.size = Pt(9)
        p_foot.font.color.rgb = TEXT_MUTED

    # 1. Slide 1: Title / Executive Slide
    slide1 = prs.slides.add_slide(blank_slide_layout)
    set_slide_background(slide1, NAVY)

    # Accent decorative bar
    bar = slide1.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(0.8), Inches(1.8), Inches(0.15), Inches(3.6))
    bar.fill.solid()
    bar.fill.fore_color.rgb = ACCENT_GOLD
    bar.line.fill.background()

    tb = slide1.shapes.add_textbox(Inches(1.2), Inches(1.8), Inches(11.0), Inches(3.6))
    tf1 = tb.text_frame
    tf1.word_wrap = True

    p_class = tf1.paragraphs[0]
    p_class.text = f"NATIONAL DEFENCE & STRATEGIC PSU ENTERPRISE  •  [{classification}]"
    p_class.font.size = Pt(12)
    p_class.font.bold = True
    p_class.font.color.rgb = ACCENT_GOLD
    p_class.space_after = Pt(14)

    p_title = tf1.add_paragraph()
    p_title.text = title
    p_title.font.size = Pt(32)
    p_title.font.bold = True
    p_title.font.color.rgb = TEXT_LIGHT
    p_title.space_after = Pt(10)

    p_sub = tf1.add_paragraph()
    p_sub.text = subtitle
    p_sub.font.size = Pt(16)
    p_sub.font.color.rgb = TEXT_MUTED
    p_sub.space_after = Pt(20)

    p_meta = tf1.add_paragraph()
    p_meta.text = f"Generated by Sovereign Air-Gapped AI Engine  |  Date: {datetime.now().strftime('%d-%b-%Y')}  |  Node: LOCAL-NODE-01"
    p_meta.font.size = Pt(11)
    p_meta.font.color.rgb = ACCENT_EMERALD

    # Default Slides if not provided
    if not slides_data:
        slides_data = [
            {
                "title": "Executive Summary & Incident Context",
                "cards": [
                    {"heading": "Inspection Scope", "text": "Comprehensive analysis of Unit #07 Turbine telemetry & field inspection scans against SOP-TURB-IND-2026-V4.", "color": CARD_BG},
                    {"heading": "Core Finding", "text": "Critical vibration spike (4.85 mm/s RMS) violating safety envelope by +38.5%. Babbitt white metal thermal trip at 94.2°C.", "color": CARD_BG},
                    {"heading": "Immediate Mandate", "text": "Mandatory Form QA-88 Note Sheet issued for emergency rotor de-energization and scheduled overhaul.", "color": CARD_BG}
                ]
            },
            {
                "title": "Discrepancy Matrix vs Sovereign SOP Standards",
                "table_headers": ["Parameter", "Measured Telemetry", "SOP Envelope Limit", "Compliance Verdict"],
                "table_rows": [
                    ["Bearing Drive-End Vibration", "4.85 mm/s RMS", "<= 3.50 mm/s (SOP Sec 2.1)", "CRITICAL BREACH (FAIL)"],
                    ["Journal Bearing Temp", "94.2 °C", "<= 90.0 °C (SOP Sec 2.2)", "THERMAL HAZARD (FAIL)"],
                    ["Lube Oil Pressure", "1.85 Bar", "1.80 - 2.20 Bar", "NORMAL (PASS)"],
                    ["Lube Oil Contamination", "NAS Class 8", "<= NAS Class 6", "DEBRIS DETECTED (WARN)"]
                ]
            },
            {
                "title": "Isolated Code Sandbox & Telemetry Analytics",
                "cards": [
                    {"heading": "Air-Gapped Sandbox", "text": "Python analytical scripts executed with socket.socket=None and 25s timeout bounds.", "color": CARD_BG},
                    {"heading": "Anomaly Window", "text": "Degradation peak recorded at 11:00:00 (Axle AX-101: 104.2°C, 1.88g vibration).", "color": CARD_BG},
                    {"heading": "Harvested Deliverables", "text": "Generated high-resolution degradation chart (.png) and formatted telemetry spreadsheet (.xlsx).", "color": CARD_BG}
                ]
            },
            {
                "title": "Action Directives & Regulatory Recommendations",
                "cards": [
                    {"heading": "1. Immediate De-Energization", "text": "Execute emergency rotor brake protocol to prevent cavitation and destructive shaft fatigue.", "color": CARD_BG},
                    {"heading": "2. Spares Procurement", "text": "Sanction replacement Babbitt journal bearings under Category-1 Strategic Reserve Budget.", "color": CARD_BG},
                    {"heading": "3. Audit & Compliance", "text": "All operations cryptographically locked into SHA-256 Chained Audit Ledger (Zero Egress).", "color": CARD_BG}
                ]
            }
        ]

    # Generate slides from slides_data
    for s_idx, s_data in enumerate(slides_data, start=2):
        slide = prs.slides.add_slide(blank_slide_layout)
        set_slide_background(slide, DARK_BG)
        add_header_footer(slide, s_data.get("title", f"Section {s_idx}"), s_idx)

        # Handle Card Layout
        if "cards" in s_data:
            cards = s_data["cards"]
            num_cards = len(cards)
            card_width = (11.733 - (num_cards - 1) * 0.4) / num_cards
            
            for c_idx, card in enumerate(cards):
                left = Inches(0.8 + c_idx * (card_width + 0.4))
                top = Inches(1.6)
                width = Inches(card_width)
                height = Inches(4.8)

                # Card Box
                box = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, left, top, width, height)
                box.fill.solid()
                box.fill.fore_color.rgb = card.get("color", CARD_BG)
                box.line.color.rgb = RGBColor(40, 60, 95)
                box.line.width = Pt(1.5)

                # Top accent line
                acc = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, left + Inches(0.2), top + Inches(0.2), width - Inches(0.4), Inches(0.06))
                acc.fill.solid()
                acc.fill.fore_color.rgb = ACCENT_GOLD if c_idx == 0 else ACCENT_EMERALD
                acc.line.fill.background()

                # Card Content
                c_tb = slide.shapes.add_textbox(left + Inches(0.2), top + Inches(0.4), width - Inches(0.4), height - Inches(0.6))
                c_tf = c_tb.text_frame
                c_tf.word_wrap = True

                p_head = c_tf.paragraphs[0]
                p_head.text = card.get("heading", "")
                p_head.font.size = Pt(16)
                p_head.font.bold = True
                p_head.font.color.rgb = TEXT_LIGHT
                p_head.space_after = Pt(12)

                p_body = c_tf.add_paragraph()
                p_body.text = card.get("text", "")
                p_body.font.size = Pt(13)
                p_body.font.color.rgb = TEXT_MUTED

        # Handle Table Layout
        elif "table_headers" in s_data and "table_rows" in s_data:
            headers = s_data["table_headers"]
            rows = s_data["table_rows"]
            
            rows_cnt = len(rows) + 1
            cols_cnt = len(headers)
            
            table_shape = slide.shapes.add_table(rows_cnt, cols_cnt, Inches(0.8), Inches(1.6), Inches(11.733), Inches(4.8))
            table = table_shape.table

            # Format Headers
            for c_idx, h_text in enumerate(headers):
                cell = table.cell(0, c_idx)
                cell.fill.solid()
                cell.fill.fore_color.rgb = NAVY
                p = cell.text_frame.paragraphs[0]
                p.text = h_text
                p.font.size = Pt(12)
                p.font.bold = True
                p.font.color.rgb = TEXT_LIGHT
                p.alignment = PP_ALIGN.CENTER

            # Format Rows
            for r_idx, r_data in enumerate(rows, start=1):
                for c_idx, val in enumerate(r_data):
                    cell = table.cell(r_idx, c_idx)
                    cell.fill.solid()
                    cell.fill.fore_color.rgb = CARD_BG if r_idx % 2 == 1 else RGBColor(16, 28, 48)
                    p = cell.text_frame.paragraphs[0]
                    p.text = str(val)
                    p.font.size = Pt(11)
                    if "FAIL" in str(val) or "CRITICAL" in str(val):
                        p.font.color.rgb = ACCENT_RED
                        p.font.bold = True
                    elif "PASS" in str(val):
                        p.font.color.rgb = ACCENT_EMERALD
                        p.font.bold = True
                    else:
                        p.font.color.rgb = TEXT_LIGHT

    # Save to deliverables directory
    timestamp_str = datetime.now().strftime('%Y%m%d_%H%M%S')
    filename = f"{filename_prefix}_{timestamp_str}.pptx"
    filepath = DELIVERABLES_DIR / filename
    prs.save(str(filepath))

    return filename

create_executive_deck = create_executive_presentation

